# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    thor_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

thor_arm_controller:
  ros__parameters:
    joints:
      - art1_yaw
      - art2_pitch
      - art3_pitch
      - art4_roll
      - art5_pitch
      - art6_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity