controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # gripper_controller:
    #   type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - art1_yaw
      - art2_pitch
      - art3_pitch
      - art4_roll
      - art5_pitch
      - art6_roll

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true
