# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_2:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_3:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_4:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_5:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_6:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripperbase_to_armgearright:
    has_velocity_limits: false
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripperbase_to_armgearleft:
    has_velocity_limits: false
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripperbase_to_armsimpleright:
    has_velocity_limits: false
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripperbase_to_armsimpleleft:
    has_velocity_limits: false
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  armgearright_to_fingerright:
    has_velocity_limits: false
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  armgearleft_to_fingerleft:
    has_velocity_limits: false
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0